require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**'
    - 'vendor/**/*'
  NewCops: enable

Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
